name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Check that code can compile
      run: cargo check

    - name: Build
      run: cargo build --verbose

    - name: Create and populate config.toml
      run: |
        cat <<EOF > config.toml
        authorization_api_url = "https://auth.example.com/api/v1/authorization"

        [[services]]
        path = "^/users"
        target_service = "http://user-service.default.svc.cluster.local"
        target_port = "8080"
        authentication_required = false

        [[services]]
        path = "^/orders"
        target_service = "http://order-service.default.svc.cluster.local"
        target_port = "8080"
        authentication_required = true
        EOF

    - name: Run tests
      run: cargo test --verbose
